version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: main
  reviewers:
  - SonyaMoisset
  assignees:
  - SonyaMoisset
  labels:
  - Dependencies
  - Security
  allow:
  - dependency-type: production
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
